### PR TITLE
Better dependencies handling and other general improvements

### PR DESCRIPTION
**Pull request by lucgirardin**
I tried to make the changes so that they don't alter the default behavior. Here are the improvements in brief:
- Reduced default amount of screen output (lowered to INFO level)
- Created us.ascendtech.gwt.dep plugin
- Added option to suppress "extra" output
- Option to force recompilation (can in principle be turned off)
- Improve detection of changes to support incremental compilation
- Update Gradle to version 5.6.2

### CODE REVIEW

**Comment by mdavis95** [comment]
Can you explain the us.ascendtech.gwt.dep plugin some?  Most of this stuff looks pretty good in theory and I am inclined to merge.

**Comment by lucgirardin** [comment]
The us.ascendtech.gwt.dep plugin tries to solve the following symptoms in multi-project setup:
If two projects "gwt" and "swing" are dependent on a "common" project, then one was forced to make "common" use the  us.ascendtech.gwt.lib plugin so that it is included in the compilation of "gwt", but has the undesirable side-effect that "common" is always recompiled irrespectively of whether it has changed or not. Making "common" use the  us.ascendtech.gwt.dep plugin solves this problem: "common" is not recompiled if there was no change and "common" is included in the GWT compilation of "gwt".

**Comment by mdavis95** [comment]
I get the following exception when testing:
```
Caused by: org.codehaus.groovy.runtime.metaclass.MethodSelectionException: Could not find which method info() to invoke from this list:
  public abstract transient void org.gradle.api.logging.Logger#info(java.lang.String, [Ljava.lang.Object;)
  public abstract void org.slf4j.Logger#info(java.lang.String)
  public abstract void org.slf4j.Logger#info(java.lang.String, java.lang.Object)
  public abstract void org.slf4j.Logger#info(java.lang.String, java.lang.Throwable)
  public abstract void org.slf4j.Logger#info(org.slf4j.Marker, java.lang.String)
  public abstract void org.slf4j.Logger#info(java.lang.String, java.lang.Object, java.lang.Object)
  public abstract transient void org.slf4j.Logger#info(org.slf4j.Marker, java.lang.String, [Ljava.lang.Object;)
  public abstract void org.slf4j.Logger#info(org.slf4j.Marker, java.lang.String, java.lang.Object)
  public abstract void org.slf4j.Logger#info(org.slf4j.Marker, java.lang.String, java.lang.Throwable)
  public abstract void org.slf4j.Logger#info(org.slf4j.Marker, java.lang.String, java.lang.Object, java.lang.Object)
        at us.ascendtech.js.npm.NpmPlugin$_apply_closure1.doCall(NpmPlugin.groovy:26)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
```

**Comment by lucgirardin** [comment]
Interesting! Which version of Java and Gradle are you using?

**Comment by mdavis95** [comment]
Java 12 / Gradle 5.6.2

It seems it just wanted
 project.logger.info("gradle npm dependencies: " + npm.dependencies)
instead of
 project.logger.info(npm.dependencies)

**Comment by lucgirardin** [comment]
Ok good! I am not using that plugin so that's why it escaped my attention...

**Comment by mdavis95** [comment]
This is available as version 0.4.20

**Comment by mdavis95** [comment]
@lucgirardin thanks for the PR

**Pull request merged**
